---
- name: Prep Pis for Clustering.
  hosts: cluster,build-server
  become: yes

  tasks:  
  - name: Upgrade the OS.
    apt:
      upgrade: dist
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600 
  
  - name: Set hostname.
    command: hostnamectl set-hostname {{ node_hostname }}

  - name: Enable container features.
    replace:
      path: /boot/firmware/cmdline.txt
      regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
      replace: '\1 {{ item }}'
    with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
    when: {{ node_arch }} == "arm64"

  - name: Reboot Pi.
    reboot:
      reboot_timeout: 3600

  - name: Download K3s install script.
    command:
      cmd: curl -sfL https://get.k3s.io > /home/{{ ansible_ssh_user }}/k3sInstall.sh
      creates: /home/{{ ansible_ssh_user }}/k3sInstall.sh
  
  - name: Change K3S install script permissions.
    file:
      path: /home/{{ ansible_ssh_user }}/k3sInstall.sh
      owner: {{ ansible_ssh_user }}
      group: {{ ansible_ssh_user }}
      mode: u+x,g+x,o+x
     
  - name: Run K3s install script.
    command:
      cmd: sh /home/{{ ansible_ssh_user }}/k3sInstall.sh
      become: yes