---
- name: Prep Pis for Clustering.
  hosts: cluster
  become: yes

  tasks:  
  - name: Upgrade the OS.
    apt:
      upgrade: dist
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600 
  
  - name: Set hostname.
    command: hostnamectl set-hostname {{ node_hostname }}

  - name: Enable container features on ubuntu.
    replace:
      path: /boot/firmware/cmdline.txt
      regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
      replace: '\1 {{ item }}'
    with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
    when: 
      - node_arch == "arm64"
      - node_distro == "ubuntu"

  - name: Enable container features on raspbian.
    replace:
      path: /boot/cmdline.txt
      regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
      replace: '\1 {{ item }}'
    with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
    when: 
      - node_arch == "arm64"
      - node_distro == "raspbian"

  - name: Reboot Pi.
    reboot:
      reboot_timeout: 3600

  - name: Download and run K3s install script.
    shell:
      cmd: curl -sfL https://get.k3s.io | sh -