name: Ansible-Linting
on: [push]
jobs:
  lint-playbooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets:
            $GITHUB_WORKSPACE/k3s-playbook.yml
            $GITHUB_WORKSPACE/etcd-playbook.yml
      - run: ls $GITHUB_WORKSPACE/
