# This is a basic workflow to help you get started with Actions

name: Ansible-Linting

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Lint Ansible Playbook
        # replace "master" with any valid ref
        uses: ansible/ansible-lint-action@master
        with:
          targets:
            /github/workspace/etcd-playbook.yml
            /github/workspace/k3s-playbook.yml
          override-deps:
            ansible==2.9
            ansible-lint==4.2.0
